window.DEMO_DATA = {
  standorte: [
    {
      standort_id: "JLS-001",
      filiale_name: "Bahnhofstrasse",
      strasse: "Bahnhofstrasse 12",
      plz: "8001",
      ort: "Zuerich",
      kanton: "ZH",
      kontaktperson: "Sandra Keller",
      telefon: "+41 44 123 45 67",
      anmeldung_noetig: true,
      anmeldung_hinweis: "Security 48h vorher anmelden",
      montagefenster: "Mo-Fr 07:00-09:00",
      parkplatz_hinweis: "Lieferzone, 30 Min."
    },
    {
      standort_id: "JLS-002",
      filiale_name: "Marktgasse",
      strasse: "Marktgasse 18",
      plz: "8400",
      ort: "Winterthur",
      kanton: "ZH",
      kontaktperson: "Peter Brunner",
      telefon: "+41 52 234 56 78",
      anmeldung_noetig: false,
      anmeldung_hinweis: "",
      montagefenster: "Mo-Sa nach Absprache",
      parkplatz_hinweis: "Innenhof"
    },
    {
      standort_id: "JLS-003",
      filiale_name: "Multergasse",
      strasse: "Multergasse 7",
      plz: "9000",
      ort: "St. Gallen",
      kanton: "SG",
      kontaktperson: "Monika Ritter",
      telefon: "+41 71 345 67 89",
      anmeldung_noetig: true,
      anmeldung_hinweis: "Hauswartung 48h vorher anmelden",
      montagefenster: "Di/Do 06:30-08:30",
      parkplatz_hinweis: "Standard"
    },
    {
      standort_id: "JLS-004",
      filiale_name: "Vordergasse",
      strasse: "Vordergasse 45",
      plz: "8200",
      ort: "Schaffhausen",
      kanton: "SH",
      kontaktperson: "Hans Mueller",
      telefon: "+41 52 456 78 90",
      anmeldung_noetig: false,
      anmeldung_hinweis: "",
      montagefenster: "Mo-Fr ganztags",
      parkplatz_hinweis: "Parkhaus 200 m"
    },
    {
      standort_id: "JLS-005",
      filiale_name: "Zuercherstrasse",
      strasse: "Zuercherstrasse 88",
      plz: "8500",
      ort: "Frauenfeld",
      kanton: "TG",
      kontaktperson: "Lisa Vogel",
      telefon: "+41 52 567 89 01",
      anmeldung_noetig: false,
      anmeldung_hinweis: "",
      montagefenster: "Mo-Fr 07:00-18:00",
      parkplatz_hinweis: "Kundenparkplatz"
    }
  ],
  rollouts: [
    {
      rollout_id: "RO-001",
      standort_id: "JLS-001",
      rollout_typ: "Austausch 55 Zoll / Migration",
      screen_typ: "QM55",
      halterung_typ: "SIP",
      ip_power: false,
      player_typ: 1,
      hohldecke: false,
      anzahl_personen: 1,
      zeitbedarf_min: 90,
      cms_status: "geprueft",
      material_status: "komplett",
      prozess_status: "bereit",
      installationsdatum: "2026-04-22",
      cluster: "A",
      team: "Team 1",
      bemerkung: "Security 48h vorher anmelden"
    },
    {
      rollout_id: "RO-002",
      standort_id: "JLS-002",
      rollout_typ: "Austausch 55 Zoll",
      screen_typ: "OM55",
      halterung_typ: "DEP",
      ip_power: true,
      player_typ: 2,
      hohldecke: false,
      anzahl_personen: 1,
      zeitbedarf_min: 150,
      cms_status: "erstellt",
      material_status: "offen",
      prozess_status: "in_bearbeitung",
      installationsdatum: "2026-04-22",
      cluster: "A",
      team: "Team 1",
      bemerkung: "Betonwand, Aufputz, Spezialbohrer"
    },
    {
      rollout_id: "RO-003",
      standort_id: "JLS-003",
      rollout_typ: "Deckenmontage 75 Zoll / Spezial",
      screen_typ: "OM75",
      halterung_typ: "DEP",
      ip_power: true,
      player_typ: 3,
      hohldecke: true,
      anzahl_personen: 2,
      zeitbedarf_min: 150,
      cms_status: "offen",
      material_status: "spezialteil offen",
      prozess_status: "blockiert",
      installationsdatum: "2026-04-23",
      cluster: "B",
      team: "Team 2",
      bemerkung: "Sonderhalterung, Leiter, Hauswartung"
    },
    {
      rollout_id: "RO-004",
      standort_id: "JLS-004",
      rollout_typ: "Austausch 55 Zoll",
      screen_typ: "QM55",
      halterung_typ: "SIHL",
      ip_power: false,
      player_typ: 1,
      hohldecke: false,
      anzahl_personen: 1,
      zeitbedarf_min: 90,
      cms_status: "geprueft",
      material_status: "komplett",
      prozess_status: "bereit",
      installationsdatum: "2026-04-23",
      cluster: "B",
      team: "Team 2",
      bemerkung: "Holzwand, Parkhaus 200 m"
    },
    {
      rollout_id: "RO-005",
      standort_id: "JLS-005",
      rollout_typ: "Austausch 75 Zoll Portrait",
      screen_typ: "QM75",
      halterung_typ: "LSM1U",
      ip_power: false,
      player_typ: 2,
      hohldecke: false,
      anzahl_personen: 1,
      zeitbedarf_min: 90,
      cms_status: "geprueft",
      material_status: "komplett",
      prozess_status: "bereit",
      installationsdatum: "2026-04-22",
      cluster: "A",
      team: "Team 1",
      bemerkung: "Problemloser Standort"
    }
  ],
  tasks: [
    {
      task_id: "TASK-001",
      rollout_id: "RO-002",
      task_typ: "Montagevorbereitung",
      titel: "Aufputzinstallation vorbereiten",
      status: "offen",
      prioritaet: "hoch",
      owner_rolle: "Montageplanung",
      faellig_am: "2026-04-18",
      quelle: "Agentenpruefung",
      hinweis: "UKV fehlt"
    },
    {
      task_id: "TASK-002",
      rollout_id: "RO-002",
      task_typ: "Konfig",
      titel: "CMS-Konfiguration pruefen",
      status: "offen",
      prioritaet: "hoch",
      owner_rolle: "Konfig",
      faellig_am: "2026-04-17",
      quelle: "Agentenpruefung",
      hinweis: "Vor Tour freigeben"
    },
    {
      task_id: "TASK-003",
      rollout_id: "RO-003",
      task_typ: "Bestellung",
      titel: "Sonderhalterung bestellen",
      status: "blockiert",
      prioritaet: "hoch",
      owner_rolle: "Einkauf",
      faellig_am: "2026-04-15",
      quelle: "Bemusterung",
      hinweis: "Spezialteil fuer Deckenmontage"
    },
    {
      task_id: "TASK-004",
      rollout_id: "RO-003",
      task_typ: "Konfig",
      titel: "CMS-Konfiguration erstellen",
      status: "offen",
      prioritaet: "hoch",
      owner_rolle: "Konfig",
      faellig_am: "2026-04-16",
      quelle: "Agentenpruefung",
      hinweis: "Player 3 noch nicht konfiguriert"
    },
    {
      task_id: "TASK-005",
      rollout_id: "RO-003",
      task_typ: "Montagevorbereitung",
      titel: "Hauswartung anmelden",
      status: "offen",
      prioritaet: "mittel",
      owner_rolle: "PL",
      faellig_am: "2026-04-18",
      quelle: "Standortvorgabe",
      hinweis: "48h vorher anmelden"
    }
  ],
  materialbedarf: [
    {
      materialbedarf_id: "MAT-001",
      rollout_id: "RO-001",
      artikel_typ: "Screen",
      artikel_code: "QM55",
      menge: 1,
      bestellstatus: "kommissioniert",
      pso_nummer: "PSO.140.101.056",
      auftragsnummer: "10156",
      hinweis: "Hauptscreen"
    },
    {
      materialbedarf_id: "MAT-002",
      rollout_id: "RO-001",
      artikel_typ: "Halterung",
      artikel_code: "SIP",
      menge: 1,
      bestellstatus: "kommissioniert",
      pso_nummer: "PSO.140.101.056",
      auftragsnummer: "10156",
      hinweis: "Passend zu QM55"
    },
    {
      materialbedarf_id: "MAT-003",
      rollout_id: "RO-001",
      artikel_typ: "Player",
      artikel_code: "PLAYER-1",
      menge: 1,
      bestellstatus: "kommissioniert",
      pso_nummer: "PSO.140.101.056",
      auftragsnummer: "10156",
      hinweis: "Player gemaess Rollout"
    },
    {
      materialbedarf_id: "MAT-004",
      rollout_id: "RO-002",
      artikel_typ: "Screen",
      artikel_code: "OM55",
      menge: 1,
      bestellstatus: "bestellt",
      pso_nummer: "PSO.140.101.057",
      auftragsnummer: "10157",
      hinweis: "Hauptscreen"
    },
    {
      materialbedarf_id: "MAT-005",
      rollout_id: "RO-002",
      artikel_typ: "Halterung",
      artikel_code: "DEP",
      menge: 1,
      bestellstatus: "offen",
      pso_nummer: "PSO.140.101.057",
      auftragsnummer: "10157",
      hinweis: "Halterung fehlt"
    },
    {
      materialbedarf_id: "MAT-006",
      rollout_id: "RO-002",
      artikel_typ: "IP Power",
      artikel_code: "IP-POWER",
      menge: 1,
      bestellstatus: "offen",
      pso_nummer: "PSO.140.101.057",
      auftragsnummer: "10157",
      hinweis: "Zusaetzliche Komponente"
    },
    {
      materialbedarf_id: "MAT-007",
      rollout_id: "RO-002",
      artikel_typ: "Player",
      artikel_code: "PLAYER-2",
      menge: 1,
      bestellstatus: "bestellt",
      pso_nummer: "PSO.140.101.057",
      auftragsnummer: "10157",
      hinweis: "Player gemaess Rollout"
    },
    {
      materialbedarf_id: "MAT-008",
      rollout_id: "RO-003",
      artikel_typ: "Screen",
      artikel_code: "OM75",
      menge: 1,
      bestellstatus: "bestellt",
      pso_nummer: "PSO.140.101.058",
      auftragsnummer: "10158",
      hinweis: "Hauptscreen"
    },
    {
      materialbedarf_id: "MAT-009",
      rollout_id: "RO-003",
      artikel_typ: "Halterung",
      artikel_code: "DEP-SPECIAL",
      menge: 1,
      bestellstatus: "offen",
      pso_nummer: "PSO.140.101.058",
      auftragsnummer: "10158",
      hinweis: "Sonderhalterung"
    },
    {
      materialbedarf_id: "MAT-010",
      rollout_id: "RO-003",
      artikel_typ: "IP Power",
      artikel_code: "IP-POWER",
      menge: 1,
      bestellstatus: "offen",
      pso_nummer: "PSO.140.101.058",
      auftragsnummer: "10158",
      hinweis: "Zusaetzliche Komponente"
    },
    {
      materialbedarf_id: "MAT-011",
      rollout_id: "RO-003",
      artikel_typ: "Player",
      artikel_code: "PLAYER-3",
      menge: 1,
      bestellstatus: "offen",
      pso_nummer: "PSO.140.101.058",
      auftragsnummer: "10158",
      hinweis: "Player gemaess Rollout"
    }
  ],
  touren: [
    {
      tour_id: "TOUR-A-2026-04-22",
      datum: "2026-04-22",
      team: "Team 1",
      fahrzeug: "Lieferwagen 1",
      status: "entwurf",
      hinweis: "Material vor Abfahrt pruefen"
    },
    {
      tour_id: "TOUR-B-2026-04-23",
      datum: "2026-04-23",
      team: "Team 2",
      fahrzeug: "Lieferwagen 2",
      status: "risiko",
      hinweis: "RO-003 noch nicht freigegeben"
    }
  ],
  tour_stopps: [
    {
      tour_stopp_id: "STOP-001",
      tour_id: "TOUR-A-2026-04-22",
      rollout_id: "RO-001",
      reihenfolge: 1,
      startzeit_plan: "07:15",
      dauer_min: 90,
      freigabe_status: "ok",
      hinweis: "Security beachten"
    },
    {
      tour_stopp_id: "STOP-002",
      tour_id: "TOUR-A-2026-04-22",
      rollout_id: "RO-005",
      reihenfolge: 2,
      startzeit_plan: "09:25",
      dauer_min: 90,
      freigabe_status: "ok",
      hinweis: "Problemloser Standort"
    },
    {
      tour_stopp_id: "STOP-003",
      tour_id: "TOUR-A-2026-04-22",
      rollout_id: "RO-002",
      reihenfolge: 3,
      startzeit_plan: "11:15",
      dauer_min: 150,
      freigabe_status: "risiko",
      hinweis: "Konfig offen, Aufputz einplanen"
    },
    {
      tour_stopp_id: "STOP-004",
      tour_id: "TOUR-B-2026-04-23",
      rollout_id: "RO-003",
      reihenfolge: 1,
      startzeit_plan: "07:30",
      dauer_min: 150,
      freigabe_status: "blockiert",
      hinweis: "Sonderhalterung fehlt"
    },
    {
      tour_stopp_id: "STOP-005",
      tour_id: "TOUR-B-2026-04-23",
      rollout_id: "RO-004",
      reihenfolge: 2,
      startzeit_plan: "10:50",
      dauer_min: 90,
      freigabe_status: "ok",
      hinweis: "Parkhaus 200 m"
    }
  ]
};
